services:
  wol_service:
    image: ghcr.io/tbrodbeck/wol-service:latest
    container_name: wol_service
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - PHX_HOST=raspi-large.bass-mora.ts.net
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_SERVER=true
    env_file:
      - .env